import type {
  DashboardStats,
  Task,
  Transaction,
  Referral,
  TaskApproval,
  AdminUser,
  WithdrawalRequest,
  AdminInfo,
  AnalyticsData,
} from "@/types";

export const mockTasks: Task[] = [
  {
    id: "task_001",
    title: "Follow & Like Instagram Post",
    description: "Follow our Instagram account and like the latest post. Take a screenshot as proof.",
    instructions: [
      "Search for @kineticbrand on Instagram",
      "Follow the account",
      "Like the most recent post",
      "Take a screenshot showing your follow and the liked post",
      "Upload the screenshot as proof",
    ],
    reward: 2.5,
    estimatedTime: "5 min",
    category: "social_media",
    difficulty: "easy",
    label: "popular",
    status: "available",
    proofTypes: ["screenshot"],
    imageUrl: undefined,
    url: "https://instagram.com/kineticbrand",
    createdBy: "advertiser_001",
    createdAt: "2024-12-01T00:00:00Z",
    deadline: "2025-01-15T00:00:00Z",
    completionsRequired: 500,
    completionsCurrent: 342,
  },
  {
    id: "task_002",
    title: "Subscribe to YouTube Channel",
    description: "Subscribe to our YouTube channel and like the latest video.",
    instructions: [
      "Visit the YouTube channel link",
      "Subscribe to the channel",
      "Like the latest video",
      "Take a screenshot of subscription confirmation",
      "Submit the screenshot as proof",
    ],
    reward: 3.0,
    estimatedTime: "5 min",
    category: "social_media",
    difficulty: "easy",
    label: "featured",
    status: "available",
    proofTypes: ["screenshot"],
    url: "https://youtube.com/@kineticbrand",
    createdBy: "advertiser_001",
    createdAt: "2024-12-02T00:00:00Z",
    deadline: "2025-01-20T00:00:00Z",
    completionsRequired: 300,
    completionsCurrent: 187,
  },
  {
    id: "task_003",
    title: "Write a Product Review",
    description: "Write a detailed review of our product on the specified platform.",
    instructions: [
      "Visit the product page",
      "Write a review with at least 100 words",
      "Include pros and cons",
      "Rate the product 4+ stars",
      "Submit the review link as proof",
    ],
    reward: 7.5,
    estimatedTime: "15 min",
    category: "content",
    difficulty: "medium",
    label: "trending",
    status: "available",
    proofTypes: ["url", "screenshot"],
    createdBy: "advertiser_002",
    createdAt: "2024-12-03T00:00:00Z",
    deadline: "2025-01-25T00:00:00Z",
    completionsRequired: 200,
    completionsCurrent: 89,
  },
  {
    id: "task_004",
    title: "Complete Survey: Consumer Habits",
    description: "Answer a 10-minute survey about your daily consumer habits and preferences.",
    instructions: [
      "Click the survey link",
      "Answer all questions honestly",
      "Complete all sections",
      "Submit the survey",
      "Take a screenshot of the completion page",
    ],
    reward: 5.0,
    estimatedTime: "10 min",
    category: "survey",
    difficulty: "easy",
    status: "available",
    proofTypes: ["screenshot"],
    createdBy: "advertiser_003",
    createdAt: "2024-12-04T00:00:00Z",
    deadline: "2025-02-01T00:00:00Z",
    completionsRequired: 1000,
    completionsCurrent: 456,
  },
  {
    id: "task_005",
    title: "Download & Rate Mobile App",
    description: "Download the app from the app store, use it for 5 minutes, and leave a rating.",
    instructions: [
      "Download the app from App Store or Play Store",
      "Create a free account",
      "Use the app for at least 5 minutes",
      "Leave a 4+ star rating",
      "Take screenshots of download and rating",
    ],
    reward: 4.0,
    estimatedTime: "10 min",
    category: "micro_task",
    difficulty: "easy",
    label: "new",
    status: "available",
    proofTypes: ["screenshot"],
    createdBy: "advertiser_001",
    createdAt: "2024-12-05T00:00:00Z",
    deadline: "2025-02-05T00:00:00Z",
    completionsRequired: 800,
    completionsCurrent: 234,
  },
  {
    id: "task_006",
    title: "Share Blog Post on Twitter",
    description: "Share our blog post on Twitter with specific hashtags and tag 2 friends.",
    instructions: [
      "Read the blog post",
      "Compose a tweet sharing the link",
      "Include #KineticRewards and #EarnOnline hashtags",
      "Tag 2 friends in the tweet",
      "Keep the tweet public",
      "Submit the tweet URL as proof",
    ],
    reward: 3.5,
    estimatedTime: "8 min",
    category: "social_media",
    difficulty: "easy",
    status: "available",
    proofTypes: ["url"],
    url: "https://blog.kineticledger.com/top-earning-tips",
    createdBy: "advertiser_002",
    createdAt: "2024-12-06T00:00:00Z",
    deadline: "2025-02-10T00:00:00Z",
    completionsRequired: 400,
    completionsCurrent: 156,
  },
  {
    id: "task_007",
    title: "Data Entry: Categorize Products",
    description: "Categorize 50 products into the correct categories based on descriptions.",
    instructions: [
      "Access the product list",
      "Read each product description",
      "Assign the correct category from the dropdown",
      "Submit all 50 categorizations",
      "Screenshot the completion summary",
    ],
    reward: 12.0,
    estimatedTime: "30 min",
    category: "micro_task",
    difficulty: "hard",
    status: "available",
    proofTypes: ["screenshot"],
    createdBy: "advertiser_003",
    createdAt: "2024-12-07T00:00:00Z",
    deadline: "2025-02-15T00:00:00Z",
    completionsRequired: 100,
    completionsCurrent: 23,
  },
  {
    id: "task_008",
    title: "Create Unboxing Video",
    description: "Film a 2-minute unboxing video of the product and upload to YouTube.",
    instructions: [
      "Receive the product (shipped separately)",
      "Film an unboxing video (minimum 2 minutes)",
      "Upload to your YouTube channel",
      "Include #KineticRewards in title",
      "Submit the YouTube link as proof",
    ],
    reward: 25.0,
    estimatedTime: "45 min",
    category: "content",
    difficulty: "hard",
    label: "featured",
    status: "available",
    proofTypes: ["url", "screenshot"],
    createdBy: "advertiser_001",
    createdAt: "2024-12-08T00:00:00Z",
    deadline: "2025-03-01T00:00:00Z",
    completionsRequired: 50,
    completionsCurrent: 12,
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "txn_001",
    type: "earning",
    amount: 5.0,
    status: "completed",
    description: "Task: Follow & Like Instagram Post",
    createdAt: "2024-12-15T10:30:00Z",
    reference: "task_001",
  },
  {
    id: "txn_002",
    type: "earning",
    amount: 3.0,
    status: "completed",
    description: "Task: Subscribe to YouTube Channel",
    createdAt: "2024-12-14T14:20:00Z",
    reference: "task_002",
  },
  {
    id: "txn_003",
    type: "referral_bonus",
    amount: 7.5,
    status: "completed",
    description: "Referral Bonus: Sarah joined via your link",
    createdAt: "2024-12-13T09:15:00Z",
    reference: "ref_001",
  },
  {
    id: "txn_004",
    type: "withdrawal",
    amount: -50.0,
    status: "completed",
    description: "Withdrawal to PayPal",
    createdAt: "2024-12-12T16:45:00Z",
    reference: "wth_001",
  },
  {
    id: "txn_005",
    type: "earning",
    amount: 7.5,
    status: "completed",
    description: "Task: Write a Product Review",
    createdAt: "2024-12-11T11:00:00Z",
    reference: "task_003",
  },
  {
    id: "txn_006",
    type: "deposit",
    amount: 100.0,
    status: "completed",
    description: "Account Deposit via Credit Card",
    createdAt: "2024-12-10T08:30:00Z",
    reference: "dep_001",
  },
  {
    id: "txn_007",
    type: "earning",
    amount: 4.0,
    status: "pending",
    description: "Task: Download & Rate Mobile App (Pending Review)",
    createdAt: "2024-12-09T13:10:00Z",
    reference: "task_005",
  },
  {
    id: "txn_008",
    type: "commission",
    amount: 2.25,
    status: "completed",
    description: "Commission from referral task completion",
    createdAt: "2024-12-08T17:00:00Z",
    reference: "com_001",
  },
];

export const mockDashboardStats: DashboardStats = {
  balance: {
    current: 2847.5,
    totalEarnings: 12450.0,
    pendingRewards: 185.5,
    referralBonus: 420.0,
    sparklineData: [120, 180, 150, 220, 280, 310, 285],
  },
  activeTasks: 5,
  completedTasks: 156,
  pendingRewards: 3,
  referralEarnings: 420.0,
  recentTransactions: mockTransactions.slice(0, 5),
  availableTasks: mockTasks.filter((t) => t.status === "available").slice(0, 6),
  weeklyEarningData: [
    { day: "Mon", amount: 45 },
    { day: "Tue", amount: 72 },
    { day: "Wed", amount: 58 },
    { day: "Thu", amount: 91 },
    { day: "Fri", amount: 65 },
    { day: "Sat", amount: 110 },
    { day: "Sun", amount: 82 },
  ],
};

export const mockReferrals: Referral[] = [
  { id: "ref_001", name: "Sarah Chen", email: "sarah.chen@email.com", joinedDate: "2024-12-13T00:00:00Z", status: "active", yield: 45.5, tasksCompleted: 12 },
  { id: "ref_002", name: "James Wilson", email: "j.wilson@email.com", joinedDate: "2024-11-28T00:00:00Z", status: "active", yield: 32.0, tasksCompleted: 8 },
  { id: "ref_003", name: "Maria Garcia", email: "maria.g@email.com", joinedDate: "2024-12-01T00:00:00Z", status: "active", yield: 67.25, tasksCompleted: 18 },
  { id: "ref_004", name: "David Kim", email: "d.kim@email.com", joinedDate: "2024-12-05T00:00:00Z", status: "pending", yield: 12.0, tasksCompleted: 3 },
  { id: "ref_005", name: "Emma Brown", email: "emma.b@email.com", joinedDate: "2024-11-15T00:00:00Z", status: "active", yield: 89.75, tasksCompleted: 24 },
  { id: "ref_006", name: "Alex Turner", email: "a.turner@email.com", joinedDate: "2024-12-10T00:00:00Z", status: "inactive", yield: 5.0, tasksCompleted: 1 },
  { id: "ref_007", name: "Lisa Park", email: "l.park@email.com", joinedDate: "2024-12-08T00:00:00Z", status: "active", yield: 28.5, tasksCompleted: 7 },
];

export const mockTaskApprovals: TaskApproval[] = [
  { id: "appr_001", taskTitle: "Follow & Like Instagram Post", userName: "John Doe", proofType: "screenshot", submittedAt: "2024-12-15T10:30:00Z", reward: 2.5, status: "pending" },
  { id: "appr_002", taskTitle: "Subscribe to YouTube Channel", userName: "Emily Rose", proofType: "screenshot", submittedAt: "2024-12-15T11:15:00Z", reward: 3.0, status: "pending" },
  { id: "appr_003", taskTitle: "Write a Product Review", userName: "Mike Johnson", proofType: "url", proofText: "https://review-site.com/my-review", submittedAt: "2024-12-15T09:00:00Z", reward: 7.5, status: "pending" },
  { id: "appr_004", taskTitle: "Share Blog Post on Twitter", userName: "Sophia Lee", proofType: "url", proofText: "https://twitter.com/user/status/123", submittedAt: "2024-12-14T16:45:00Z", reward: 3.5, status: "approved" },
  { id: "appr_005", taskTitle: "Complete Survey: Consumer Habits", userName: "Tom Wilson", proofType: "screenshot", submittedAt: "2024-12-14T14:20:00Z", reward: 5.0, status: "rejected" },
  { id: "appr_006", taskTitle: "Download & Rate Mobile App", userName: "Anna Smith", proofType: "screenshot", submittedAt: "2024-12-14T12:00:00Z", reward: 4.0, status: "pending" },
  { id: "appr_007", taskTitle: "Create Unboxing Video", userName: "Chris Evans", proofType: "url", proofText: "https://youtube.com/watch?v=abc123", submittedAt: "2024-12-13T18:30:00Z", reward: 25.0, status: "pending" },
];

export const mockAdminUsers: AdminUser[] = [
  { id: "usr_001", name: "Alex Morgan", email: "alex@email.com", role: "earner", status: "active", balance: 2847.5, joinedDate: "2024-01-15T00:00:00Z", lastActive: "2024-12-15T10:30:00Z", tasksCompleted: 156 },
  { id: "usr_002", name: "Sarah Chen", email: "sarah@email.com", role: "earner", status: "active", balance: 1250.0, joinedDate: "2024-03-20T00:00:00Z", lastActive: "2024-12-15T09:00:00Z", tasksCompleted: 89 },
  { id: "usr_003", name: "James Wilson", email: "james@email.com", role: "advertiser", status: "active", balance: 5000.0, joinedDate: "2024-02-10T00:00:00Z", lastActive: "2024-12-14T16:00:00Z", tasksCompleted: 0 },
  { id: "usr_004", name: "Maria Garcia", email: "maria@email.com", role: "earner", status: "pending", balance: 320.0, joinedDate: "2024-12-01T00:00:00Z", lastActive: "2024-12-14T11:30:00Z", tasksCompleted: 12 },
  { id: "usr_005", name: "David Kim", email: "david@email.com", role: "earner", status: "banned", balance: 75.0, joinedDate: "2024-06-15T00:00:00Z", lastActive: "2024-10-20T08:00:00Z", tasksCompleted: 3 },
  { id: "usr_006", name: "Emma Brown", email: "emma@email.com", role: "earner", status: "active", balance: 4120.0, joinedDate: "2024-01-25T00:00:00Z", lastActive: "2024-12-15T08:00:00Z", tasksCompleted: 234 },
  { id: "usr_007", name: "Michael Chen", email: "m.chen@email.com", role: "advertiser", status: "active", balance: 8500.0, joinedDate: "2024-04-05T00:00:00Z", lastActive: "2024-12-13T14:00:00Z", tasksCompleted: 0 },
];

export const mockWithdrawalRequests: WithdrawalRequest[] = [
  { id: "wth_001", userName: "Alex Morgan", userEmail: "alex@email.com", amount: 150.0, method: "paypal", status: "pending", requestDate: "2024-12-15T08:00:00Z", accountDetails: "alex@paypal.com" },
  { id: "wth_002", userName: "Sarah Chen", userEmail: "sarah@email.com", amount: 250.0, method: "bank_transfer", status: "processing", requestDate: "2024-12-14T10:00:00Z", processedDate: "2024-12-15T09:00:00Z", accountDetails: "****4521" },
  { id: "wth_003", userName: "James Wilson", userEmail: "james@email.com", amount: 500.0, method: "crypto", status: "completed", requestDate: "2024-12-13T14:00:00Z", processedDate: "2024-12-14T10:00:00Z", accountDetails: "0x1234...5678" },
  { id: "wth_004", userName: "Emma Brown", userEmail: "emma@email.com", amount: 75.0, method: "paypal", status: "pending", requestDate: "2024-12-15T07:30:00Z", accountDetails: "emma@paypal.com" },
  { id: "wth_005", userName: "David Kim", userEmail: "david@email.com", amount: 100.0, method: "bank_transfer", status: "rejected", requestDate: "2024-12-12T16:00:00Z", accountDetails: "****7890" },
];

export const mockAdminInfo: AdminInfo[] = [
  { id: "adm_001", name: "Sarah Connor", email: "sarah.connor@kineticledger.com", role: "admin", status: "active", assignedTasks: 45, approvalRate: 94.2, joinedDate: "2024-01-01T00:00:00Z" },
  { id: "adm_002", name: "John Price", email: "john.price@kineticledger.com", role: "admin", status: "active", assignedTasks: 38, approvalRate: 91.8, joinedDate: "2024-02-15T00:00:00Z" },
  { id: "adm_003", name: "Lisa Wang", email: "lisa.wang@kineticledger.com", role: "admin", status: "active", assignedTasks: 52, approvalRate: 96.1, joinedDate: "2024-03-01T00:00:00Z" },
  { id: "adm_004", name: "Marcus Johnson", email: "m.johnson@kineticledger.com", role: "admin", status: "pending", assignedTasks: 12, approvalRate: 88.5, joinedDate: "2024-11-01T00:00:00Z" },
];

export const mockAnalyticsData: AnalyticsData = {
  totalUsers: 12450,
  activeUsers: 8920,
  totalRevenue: 284500,
  commissionEarned: 42675,
  tasksCompleted: 89340,
  pendingApprovals: 234,
  pendingWithdrawals: 18,
  totalVolume: 1250000,
  monthlyGrowth: 12.5,
  userGrowthData: [
    { month: "Jul", users: 7200 },
    { month: "Aug", users: 8100 },
    { month: "Sep", users: 8900 },
    { month: "Oct", users: 9800 },
    { month: "Nov", users: 11200 },
    { month: "Dec", users: 12450 },
  ],
  revenueData: [
    { month: "Jul", revenue: 35000, commission: 5250 },
    { month: "Aug", revenue: 42000, commission: 6300 },
    { month: "Sep", revenue: 38000, commission: 5700 },
    { month: "Oct", revenue: 51000, commission: 7650 },
    { month: "Nov", revenue: 58000, commission: 8700 },
    { month: "Dec", revenue: 60500, commission: 9075 },
  ],
  taskCompletionData: [
    { month: "Jul", completed: 12400, rejected: 620 },
    { month: "Aug", completed: 14200, rejected: 710 },
    { month: "Sep", completed: 13800, rejected: 690 },
    { month: "Oct", completed: 16500, rejected: 825 },
    { month: "Nov", completed: 18100, rejected: 905 },
    { month: "Dec", completed: 14340, rejected: 717 },
  ],
};
